Use ps instead of lshal for seccomp tests
lshal does not return PID on non debug builds.

Addresses:
Stack Trace for testConfigStoreHalHasSeccompFilter:
junit.framework.AssertionFailedError: android.hardware.configstore
process not found.

Fixes: 65688682
Test: cts-tradefed run cts -m CtsSecurityHostTestCases -t
    android.security.cts.ProcessMustUseSeccompTest
Change-Id: Ib89f256e2446277b1d743a81c52c4fc390b9d212

Former-commit-id: 0b15fb37de9936e9417c8728cf643ada26934711