Fix test failure caused by setting device to use 24 hour format
Prior to this change the test passed when the user setting
"Use 24 Hour Format" is off and failed with the message
AssertionFailedError: expected:<5:30:15 AM> but was:<05:30:15>
when run with the setting turned on.

There is no public API for checking the setting from within
this test therefore there is no way to check that the result is
what is expected for the current setting.

After this change the test accepts the expected value for 12
hour format and 24 hour format so it now passes irrespective of
whether the setting is on or off.

Bug: 31331290
Test: Ran cts-tradefed run cts -m CtsTextTestCases -t android.text.format.cts.DateUtilsTest#testFormatSameDayTime
Change-Id: I5280e48ec3e0af10ec771c38589bd3850889514e

Former-commit-id: e412076713b49e9a353231247982ae3f753773e5