cts: define march=armv7-a for 32-bit armv8-a tests
ARMv8 does not support SWP instructions, so this test is to be
sure that SWP is emulated. Without this commit, the following
error is generated on ARMv8 while compiling the CPU Instructions
test:

error: instruction requires: armv7 or earlier
asm volatile ( "swp r0, r0, [%0]" : "+r"(ptr) : : "r0" );

Bug: 64964151
Test: lunch aosp_arm64-userdebug; make -j cts
      lunch aosp_x86-userdebug; make -j cts
      lunch aosp_sailfish-userdebug; make -j cts
      lunch aosp_bullhead-userdebug; make -j cts

Change-Id: Icdf03ffeb94047cfe84826ee2a88f33bd9bbdf79

Former-commit-id: a6faed2962af623b14c61f1252c7a0b7c2861a90